### PR TITLE
No jq

### PR DESCRIPTION
**Pull request by KitaitiMakoto**
Branched from #27 .

Now we don't need `jq` command at all!

### CODE REVIEW

**Comment by kou** [comment]
Could you rebase on master?

**Comment by KitaitiMakoto** [comment]
Sure, will do later.

**Comment by KitaitiMakoto** [comment]
@kou 
I rebased this branch.

**Comment by kou** [comment]
Thanks!

**Comment by KitaitiMakoto** [comment]
Thank you!

**Pull request merged**
